# Generated by Django 3.2.5 on 2022-01-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan_generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='disance',
            new_name='distance',
        ),
    ]
