# Generated by Django 3.2.5 on 2022-06-25 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('plan_generator', '0004_auto_20220625_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile'),
        ),
    ]
