# Generated by Django 3.2.5 on 2022-06-25 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('plan_generator', '0005_alter_activity_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='account.profile'),
        ),
    ]
