# Generated by Django 3.2.5 on 2022-06-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_generator', '0006_alter_activity_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
