# Generated by Django 3.2.5 on 2022-06-25 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("plan_generator", "0008_alter_activity_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="day",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="day",
                to="account.profile",
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="day",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="plan_generator.day",
            ),
        ),
    ]
