# Generated by Django 3.2.5 on 2022-06-25 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_generator", "0009_auto_20220625_2004"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="day",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="plan_generator.day",
            ),
        ),
    ]
