# Generated by Django 3.2.5 on 2022-06-25 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("plan_generator", "0010_alter_activity_day"),
    ]

    operations = [
        migrations.AlterField(
            model_name="day",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days",
                to="account.profile",
            ),
        ),
    ]
