# Generated by Django 3.2.5 on 2022-06-26 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("plan_generator", "0012_alter_activity_activity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="end_volume",
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="volume_metric",
            field=models.CharField(
                choices=[
                    ("TIME", "Time"),
                    ("DISTANCE", "Distance"),
                    ("ASCENT", "Ascent"),
                ],
                default="TIME",
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="week",
            name="distance",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="week",
            name="plan",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="plan_generator.trainingplan",
            ),
        ),
        migrations.AddField(
            model_name="week",
            name="plan_distance",
            field=models.FloatField(default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="week",
            name="plan_time",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="week",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weeks",
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="week",
            name="time",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="activity",
            name="activity_type",
            field=models.CharField(
                choices=[("Run", "Run"), ("Ride", "Ride"), ("Walk", "Walk")],
                default="Run",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="start_date",
            field=models.DateField(unique=True),
        ),
    ]
