# Generated by Django 3.2.5 on 2022-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_generator', '0013_auto_20220626_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
