# Generated by Django 3.2.5 on 2022-06-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        ("plan_generator", "0014_alter_day_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingplan",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="profile",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.profile",
            ),
        ),
        migrations.AddField(
            model_name="trainingplan",
            name="start_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="week",
            name="plan_time",
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name="week",
            name="start_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="week",
            name="time",
            field=models.DurationField(),
        ),
    ]
