# Generated by Django 3.2.5 on 2022-06-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_generator', '0016_auto_20220626_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='strava_id',
            field=models.BigIntegerField(null=True),
        ),
    ]
