# Generated by Django 3.2.5 on 2022-06-26 20:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plan_generator", "0019_auto_20220626_2052"),
    ]

    operations = [
        migrations.AlterField(
            model_name="week",
            name="plan_time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name="week",
            name="time",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
